spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.31.58/sell?characterEncoding=utf-8&useSSL=false
#    url: jdbc:mysql://192.168.43.102/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    #返回给前台的值为null的话不显示
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.31.58
#    host: 192.168.43.102
    port: 6379
server:
  context-path: /sell
  port: 8084

#微信
wechat:
  #微信测试公众号的appid,和appsecret
  mpAppId: wxc81905d0adc5a59f
  mpAppSecret: dd81bc78d95c9e116cffe38282fde3d8



  #借用师兄的appid,和appsecret
  #mpAppId: wxd898fcb01713c658
  #mpAppSecret: 4e61dc329ae11f895eb16d99b8c3bec9

  mchId: 1483469312
  mchKey: C5245D70627C1F8E9964D494B0735025

  #微信开发平台
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  #keyPath: /your/path/h5.p12 #证书文件的完整路径，证书下载：课程源码doc目录下的h5.p12
  #微信支付的商户号，商户秘钥，商户证书存放路径
  #mchId: 1409146202
  #mchKey: c976503d34ca432c601361f969fd8d85
  #支付不需要证书，退款需要证书
  keyPath: D:\IDEAproject\sell\src\main\resources\static\cert\h5.p12

  #异步通知，没有写异步通知，不能发起支付
  notifyUrl: http://university.natapp1.cc/sell/pay/notify
  templateId:
    #测试公众号的模板Id
    orderStatus: HSuWSjoZp_CTOlMFVyuOIiMCVcXeS7g4uzxYG1lF--Q
    orderStatus1: 4I1kMveCrwFi9XO8IJHzknq7iUqiKUs4dzbzLjOQh0w
    orderStatus2: ZJQEoysd1xwrXVvWsXKntNp5_N5MCLXbhmS7nHCT1aA
projectUrl:
  wechatMpAuthorize: http://university.natapp1.cc
  wechatOpenAuthorize: http://university.natapp1.cc
  sell: http://university.natapp1.cc
logging:
  level:
    com.university.dataobject.mapper: trace
mybatis:
  mapper-locations: classpath:mapper/*.xml